### ISSUE TITLE
CamillaDSP GUI error message

### ISSUE THREAD

**Issue by balbuze** [HEnquist/camilladsp#259]
RPI4
Volumio 3.396
CamillaDSP 1.0.2
pyCamillaDSP 1.0.0
Backend 1.0.0
On a working system, when play stops, the message : 
```
Traceback (most recent call last):
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 406, in start
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     resp = await task
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 435, in _handle
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     resp = await handler(request)
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/data/plugins/audio_interface/fusiondsp/cgui/backend/views.py", line 90, in get_param
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     result = cdsp.get_volume()
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 276, in get_volume
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     vol = self._query("GetVolume")
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 134, in _query
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     raise IOError("Not connected to CamillaDSP")
Jan 12 17:40:18 volumio-rpi4 volumio[1155]: OSError: Not connected to CamillaDSP
Jan 12 17:40:18 volumio-rpi4 volumio[1155]: ERROR:aiohttp.server:Error handling request
Jan 12 17:40:18 volumio-rpi4 volumio[1155]: Traceback (most recent call last):
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 406, in start
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     resp = await task
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 435, in _handle
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     resp = await handler(request)
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/data/plugins/audio_interface/fusiondsp/cgui/backend/views.py", line 92, in get_param
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     result = cdsp.get_mute()
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 289, in get_mute
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     mute = self._query("GetMute")
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 134, in _query
Jan 12 17:40:18 volumio-rpi4 volumio[1155]:     raise IOError("Not connected to CamillaDSP")
Jan 12 17:40:18 volumio-rpi4 volumio[1155]: OSError: Not connected to CamillaDSP
Jan 12 17:40:19 volumio-rpi4 volumio[1155]: ERROR:aiohttp.server:Error handling request
Jan 12 17:40:19 volumio-rpi4 volumio[1155]: Traceback (most recent call last):
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 406, in start
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     resp = await task
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 435, in _handle
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     resp = await handler(request)
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/data/plugins/audio_interface/fusiondsp/cgui/backend/views.py", line 90, in get_param
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     result = cdsp.get_volume()
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 276, in get_volume
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     vol = self._query("GetVolume")
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 134, in _query
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     raise IOError("Not connected to CamillaDSP")
Jan 12 17:40:19 volumio-rpi4 volumio[1155]: OSError: Not connected to CamillaDSP
Jan 12 17:40:19 volumio-rpi4 volumio[1155]: ERROR:aiohttp.server:Error handling request
Jan 12 17:40:19 volumio-rpi4 volumio[1155]: Traceback (most recent call last):
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 406, in start
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     resp = await task
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 435, in _handle
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     resp = await handler(request)
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/data/plugins/audio_interface/fusiondsp/cgui/backend/views.py", line 92, in get_param
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     result = cdsp.get_mute()
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 289, in get_mute
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     mute = self._query("GetMute")
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:   File "/usr/local/lib/python3.7/dist-packages/camilladsp/camilladsp.py", line 134, in _query
Jan 12 17:40:19 volumio-rpi4 volumio[1155]:     raise IOError("Not connected to CamillaDSP")
```
is repeated every second. But stop when it plays something.
What is the reason?

**Comment by HEnquist** [comment]
The message means that camilladsp isn't running. Then the gui tries to reconnect once per second. Are you using the alsa_cdsp plugin?

**Comment by balbuze** [comment]
In volumio we use https://github.com/volumio/volumio-alsa-hook + https://github.com/volumio/volumio-alsa-fifo developped for that use because mpd was hanging when used with alsa_cdsp and this part is added in asound.conf : 
```
#------ FusionDsp section -------
pcm.volumioDsp {
  type plug
  slave.pcm "fusiondsphook"
}

pcm.fusiondsphook {
  type volumiohook
  slave.pcm "fusiondspfifo"
  hw_params_command "/data/plugins/audio_interface/fusiondsp/camilladsp -p 9876 -l warn -o /tmp/camilladsp.log -r %r -f $(echo '%f' | sed 's/_//') -n %c /data/configuration/audio_interface/fusiondsp/camilladsp.yml &"
  hw_free_command "tail --pid `pidof camilladsp` -f /dev/null"
  debug 1
}

pcm.fusiondspfifo {
  type volumiofifo
  fifo "/tmp/fusiondspfifo"
  format_3 "S16_LE"
  format_4 "S24_LE"
  format_5 "S32_LE"
}
#------ End of FusionDsp section ------

**Comment by HEnquist** [comment]
Ok then it works the same way as with alsa_cdsp. Camilladsp is launched when the fusiondsphook is opened, and exits when it's closed. So this is working as expected.

**Comment by balbuze** [comment]
So ok. No worries about the message.
Thanks for the info.
Regards
